### PR TITLE
Upgrades dependencies

### PR DESCRIPTION
**Pull request by clarkie**

### CODE REVIEW

**Comment by clarkie** [comment]
@cdhowie @dangerginger thoughts?

I've added you both as collaborators btw ;)

**Comment by dangerginger** [comment]
@clarkie I will look at this and get back to you this weekend.  Thanks for inviting me to be a collaborator!

**Comment by cdhowie** [comment]
I'm a bit worried that the use of specific versions in dependencies will cause dependency conflicts with other packages that might do the same thing. Is there some set of best practices we're following that indicates this is preferred?

**Comment by clarkie** [comment]
Ah yeah, sorry, that's my fault. In our own projects at Tido we pin to specific versions. We got burnt by a public package not following semver so I changed my machine to pin them by default. I'll fix these so they're fuzzy

**Comment by clarkie** [comment]
Although, actually, they weren't fuzzy before, hmmmm.

**Comment by clarkie** [comment]
I'm not sure you'd get a conflict as such as an `npm install` can handle install multiple versions of the same package: e.g.
image

**Comment by cdhowie** [comment]
Right, I forgot that npm does that now.

**Comment by dangerginger** [comment]
Yeah even though you can install multiple versions of a package doesn't necessarily mean there won't be any problems if the components expose their `joi` schemas.  I think version pinning is a good idea because you can make a PR like this and ensure the tests all pass.

The potential problem would be one dependency creates a v10.6 joi schema and then another dependency tries to use it with only v8.1.  I'm not sure that will be the case, but the schema do get created and passed around as components for the dynogels models.

I like the version pinning.

**Pull request merged**
