### PR TITLE
#42 Add `usingIndex` method to scan

### PR DESCRIPTION
**Pull request by M1chaelTran**
#42

### CODE REVIEW

**Comment by clarkie** [comment]
Thanks @M1chaelTran. Any chance we could get a test for this? Thanks

**Comment by M1chaelTran** [comment]
sorry, i haven't had time or the knowledge at the moment to write test for this change.

if anyone else that need this function, please feel free to add test to it.

thank you in advance

**Comment by dangerginger** [comment]
Looks like this is now a duplicate with #45.

**Comment by cdhowie** [comment]
@dangerginger I think Github changed the way PRs associated with issues get handled.  It effectively merged the two, so closing this issue also closed the PR. Should we reopen?

**Pull request closed without merging**
