### PR TITLE
Updating requires the item already exists

### PR DESCRIPTION
**Pull request by dangerginger**

### CODE REVIEW

**Comment by dangerginger** [comment]
This fixes #51, but I need to fix some of the other unit tests that now fail because they rely on creating new items with .update().

**Comment by dangerginger** [comment]
fixes #51

**Comment by clarkie** [comment]
@dangerginger thanks for all your input recently. I'm concerned as how this and #52 will work when using both hash and range keys. 
Also, I can't find it in the docs but does adding these constraints use any extra RCU or WCU?

**Comment by deedw** [comment]
I think that this change would break code that relies on current functionality and departs from the expected functionality of the underlying DynamoDb calls.

I use .update() when I want to create or update an item using the fields I am providing without losing any existing field values that the database is already storing - effectively an upsert. When I don't want to create an item if it doesn't already exist then I add a conditional.

I use .create() when I know that I want to create (or overwrite) an item with the specific fields I am providing. I use conditionals when I don't want to overwrite an item.

The proposed approach relies on the opposite logic to this and would require multiple calls to the database to achieve the same outcome.

The underlying DynamoDb call is .updateItem() whose functionality is defined as "Edits an existing item's attributes, or adds a new item to the table if it does not already exist."

If there is a change to be made to .update() I would recommend that it should be addition of an optional property to the params to indicate that item should already exist when updating. The default should be existing functionality.

Apologies if I have misunderstood this change.

**Comment by dangerginger** [comment]
@deedw agreed.

See #53 for a better non-breaking solution to this issue

**Pull request closed without merging**
