### PR TITLE
fix readme

### PR DESCRIPTION
**Pull request by nikgraf**
Either I'm misunderstanding or there the Readme should be fixed here :)

### CODE REVIEW

**Comment by clarkie** [comment]
Haha, yes, thanks. The repo is a year older 😄

**Comment by nikgraf** [comment]
@clarkie what do you mean by the repo is a year older?

**Comment by clarkie** [comment]
@nikgraf it was a joke because you changed the age of the person in the example

**Comment by nikgraf** [comment]
ohhh, lol - I got really confused ;)

**Pull request merged**
