### PR TITLE
Fix #14 by encoding non-alpha characters in attribute keys

### LINKED ISSUE #14: Update Item
Pls, help me with updating nested values in my complex item with this.MapModel.updateAsync(mapData).
Is it possible?

```
{
  "map-url": "http://go.com/map",
  "access": 1,
  "price": 35.58,
  "folder": "some folder",
  "valid-from": "32/23/3222",
  "valid-until": "25/5/8545",
  "mapId": "2da491f6-65e7-478b-8231-da6baba9779c",
  "icon-url": "http://some.com/icon",
  "createdAt": "2016-07-25T15:55:20.308Z",
  "name": "test",
  "pois": [
    {
      "id": "43443",
      "phone": "+38055645",
      "category": "cat",
      "details": "long text long textlong textlong textlong textlong textlong textlong text",
      "location": {
        "long": 53.33222,
        "lat": 43.434333
      },
      "address": {
        "zip": "04050",
        "street": "pimonenko",
        "state": "jit",
        "city": "kiev"
      },
      "valid-from": "32/23/3222",
      "name": "fffdfd",
      "valid-until": "25/5/8545"
    },
    {
      "id": "43443",
      "phone": "+38055645",
      "category": "cat",
      "details": "long text long textlong textlong textlong textlong textlong textlong text",
      "location": {
        "long": 53.33222,
        "lat": 43.434333
      },
      "address": {
        "zip": "04050",
        "street": "pimonenko",
        "state": "jit",
        "city": "kiev"
      },
      "valid-from": "32/23/3222",
      "name": "fffdfd",
      "valid-until": "25/5/8545"
    }
  ],
  "area-coordinates": {
    "to": {
      "long": 53.33222,
      "lat": 43.434333
    },
    "from": {
      "long": 53.33222,
      "lat": 43.434333
    }
  }
}
```

### PR DESCRIPTION
**Pull request by cdhowie**

### CODE REVIEW

**Comment by cludden** [comment]
@cdhowie what's the status on this fix?

**Comment by cdhowie** [comment]
Status is "should work" but OP of #14 hasn't reported any results using it.

**Comment by cludden** [comment]
@cdhowie thanks for the follow up. @javatask can you confirm this fixes your issue so we can get this merged. We too have this issue and would like to see it merged as soon as possible.

**Comment by cdhowie** [comment]
This was fixed incorrectly by 7222db662004764dcbf2b9bd719dbbc895674922. I am rebasing my patch against v7.1.0 and removing the changes introduced by this commit.

**Comment by cludden** [comment]
@cdhowie will you be updating this PR with your changes?

**Comment by cdhowie** [comment]
@cludden I plan to but have not had time lately to work on it.

**Comment by C45tr0** [comment]
What was wrong with the 7222db6 change? Just wondering if it is preference or a situation it is not handling. 

This change looks to be doing the same thing, except you are replacing the characters with a 4 digit equivalent where the 7222db6 is just removing them. 

Also, this change looks like it would break expression document paths.

**Comment by cdhowie** [comment]
@C45tr0 The problem arises when you strip out special characters, leaving two attributes with the same cleaned key.  Encoding each non-ASCII character as a number prevents this, as every possible attribute key is guaranteed a distinct representation as a cleaned key.

**Comment by C45tr0** [comment]
@cdhowie Fair point. I took the liberty to make these changes after the Document paths changes. I will be submitting a PR with that shortly.

**Comment by cdhowie** [comment]
Superseded by #115.

**Pull request closed without merging**
